import './globals.css'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import StaticSidebarForDesktop from '@/components/StaticSidebarForDesktop'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full bg-white" data-theme="mytheme">
      <body className={inter.className + " h-full"} suppressHydrationWarning={true}>
        <div>
          {/* Static sidebar for desktop */}
          <StaticSidebarForDesktop />
          <Layout>
            {children}
          </Layout>
        </div>
      </body>
    </html>
  )
}
